/* Generated by Together */

package model;

import java.sql.Date;
public class Member {
    public Member() {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public String getLastName() {
    }

    public void setLastName(String lastName) {
    }

    public String getFirstName() {
    }

    public void setFirstName(String firstName) {
    }

    public String getPassword() {
    }

    public void setPassword(String password) {
    }

    public String getSalt() {
    }

    public void setSalt(String salt) {
    }

    public String getEmail() {
    }

    public void setEmail(String email) {
    }

    public String getAddress() {
    }

    public void setAddress(String address) {
    }

    public String getPhoneNumber() {
    }

    public void setPhoneNumber(String phoneNumber) {
    }

    public Date getRegistrationDate() {
    }

    public void setRegistrationDate(Date registrationDate) {
    }

    public Date getLastActivityDate() {
    }

    public void setLastActivityDate(Date lastActivityDate) {
    }

    public Member register() {
    }

    public Boolean login() {
    }

    public Boolean logout() {
    }

    public Teacher isTeacher() {
    }

    public Student isStudent() {
    }

    public Role getRole() {
    }

    public void setRole(Role role) {
    }

    private int id;
    private String lastName;
    private String firstName;
    private String password;
    private String salt;
    private String email;
    private String address;
    private String phoneNumber;
    private Date registrationDate;
    private Date lastActivityDate;
}
