/* Generated by Together */

package model;

import java.sql.Date;
public class Session {
    public Session() {
    }

    public int getId() {
    }

    public Date getDate() {
    }

    public Course getCourse() {
    }

    public float calculateAttendanceRate() {
    }

    public Student getParticipations() {
    }

    public void setParticipations(Student participations) {
    }

    private int id;
    private Date date;

    /**
     * @label participates
     * @supplierCardinality 0..*
     * @labelDirection reverse 
     */
    private Student participations;
}
