/* Generated by Together */

package model;

public class Student extends Member {
    public Student() {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public Course getCourses() {
    }

    public void setCourses(Course courses) {
    }

    public void markParticipation() {
    }

    public Boolean registerToCourse() {
    }

    public float calculateAttendanceRate() {
    }

    private int id;

    /**
     * @label participates
     * @supplierCardinality 0..*
     * @directed
     * @labelDirection forward 
     */
    private Course courses;
}
