/* Generated by Together */

package model;

public class Teacher extends Member {
    public Teacher() {
    }

    public Course makeCourse() {
    }

    public Session makeSession(Course course) {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public Course getCourses() {
    }

    public void setCourses(Course courses) {
    }

    private int id;

    /**
     * @label creates
     * @supplierCardinality 0..*
     * @clientCardinality 1 
     */
    private Course courses;
}
