/* Generated by Together */
import java.sql.Date;

public class Course {
    public Course() {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public String getName() {
    }

    public void setName(String name) {
    }

    public model.Teacher getTeacher() {
    }

    public Date getRegisterDate() {
    }

    public Date getStartDate() {
    }

    public model.Course registerCourse() {
    }

    public Boolean registerStudent(model.Member student) {
    }

    public model.Session addSession() {
    }

    public float calculateAttendanceRate() {
    }

    public model.Session getSession() {
    }

    public void setSession(model.Session session) {
    }

    public model.Student getRegisteredStudents() {
    }

    public void setRegisteredStudents(model.Student registeredStudents) {
    }

    private int id;
    private String name;
    private Date registerDate;
    private Date startDate;
    private model.Session session;

    /**
     * @shapeType AssociationLink 
     * @bidirectional <oiref:java#Member#Teacher#attribute1:oiref>
     * @label creaters
     * @supplierCardinality 0..*
     * @clientCardinality 1
     */
    /*# private Teacher attribute1; */

    /**
     * @shapeType AssociationLink 
     * @bidirectional
     */
    /*# private Session attribute2; */
}
