/* Generated by Together */

public class Role {
    public Role() {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public String getName() {
    }

    public void setName(String name) {
    }

    public model.Member getMembers() {
    }

    public void setMembers(model.Member members) {
    }

    private int id;
    private String name;
    private model.Member members;

    /**
     * @shapeType AssociationLink 
     * @bidirectional
     */
    /*# private Member attribute1; */
}
