/* Generated by Together */
import java.sql.Date;

public class Session {
    public Session() {
    }

    public int getId() {
    }

    public Date getDate() {
    }

    public model.Course getCourse() {
    }

    public float calculateAttendanceRate() {
    }

    public model.Student getParticipations() {
    }

    public void setParticipations(model.Student participations) {
    }

    private int id;
    private Date date;

    /**
     * @labelDirection reverse 
     */
    private model.Student participations;

    /**
     * @shapeType AssociationLink 
     * @bidirectional <oiref:java#Member#Course#attribute2:oiref>
     * @label
     * @supplierCardinality 0..*
     * @link aggregationByValue
     */
    /*# private Course attribute1; */

    /**
     * @shapeType AssociationLink 
     * @bidirectional
     */
    /*# private Student attribute2; */
}
