/* Generated by Together */

public class Student extends Member {
    public Student() {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public model.Course getCourses() {
    }

    public void setCourses(model.Course courses) {
    }

    public void markParticipation() {
    }

    public Boolean registerToCourse() {
    }

    public float calculateAttendanceRate() {
    }

    private int id;

    /**
     * @labelDirection forward 
     */
    private model.Course courses;

    /**
     * @shapeType AssociationLink 
     * @bidirectional <oiref:java#Member#Session#attribute2:oiref>
     * @label participates
     * @supplierCardinality 0..*
     * @labelDirection reverse
     */
    /*# private Session attribute1; */

    /**
     * @shapeType AssociationLink 
     * @label participates
     * @supplierCardinality 0..*
     * @directed
     * @labelDirection forward
     */
    /*# private Course attribute2; */
}
