/* Generated by Together */



public class Teacher extends Member {
    public Teacher() {
    }

    public model.Course makeCourse() {
    }

    public model.Session makeSession(model.Course course) {
    }

    public int getId() {
    }

    public void setId(int id) {
    }

    public model.Course getCourses() {
    }

    public void setCourses(model.Course courses) {
    }




    private int id;
    private model.Course courses;

    /**
     * @shapeType AssociationLink 
     * @bidirectional
     */
    /*# private Course attribute1; */
}
